calculator/urls.py
# coding=utf-8
from django.conf.urls import patterns, url
from .views import ajax_calculator_reset, VehicleProductCalculator, PropertyProductCalculator, TravelProductCalculator, \
    HealthProductCalculator, OnlinePaymentFormView, check_payment



urlpatterns = patterns(
    '',
    url(r'^modal/$', view=ajax_calculator_reset, name='general_product_calculator'),
    url(r'^modal/vehicle/$', view=VehicleProductCalculator.as_view(), name='vehicle_product_calculator'),
    url(r'^modal/property/$', view=PropertyProductCalculator.as_view(), name='property_product_calculator'),
    url(r'^modal/travel/$', view=TravelProductCalculator.as_view(), name='travel_product_calculator'),
    url(r'^modal/health/$', view=HealthProductCalculator.as_view(), name='health_product_calculator'),

    # online-оплата
    url(r'^online_payment_form/$', view=OnlinePaymentFormView.as_view(), name='online_payment_form'),
    url(r'^check_payment/(?P<product>(vehicle))/(?P<key>[0-9A-Za-z-]{36})/$', view=check_payment, name='check_payment'),
)

lib/urls.py
# coding=utf-8

from django.conf.urls import patterns, url
from django.contrib.auth import views as auth_views
from .forms import CustomPasswordResetForm

urlpatterns = patterns(
    'lib.views',

    # Управление учетными записями
    url(r'^login/$',
       view=auth_views.login,
       name='login',
       kwargs={'template_name': 'lib/login.html'}),
    url(r'^logout/$',
       view=auth_views.logout,
       name='logout',
       kwargs={'template_name': 'lib/logout.html'}),

    # Смена пароля
    url(r'^password_change/$', view=auth_views.password_change,
       name='password_change',
       kwargs={'template_name': 'lib/password_change.html',
               'post_change_redirect': '/password_change_done/'}),
    url(r'^password_change_done/$',
       view=auth_views.password_change_done,
       name='password_change_done',
       kwargs={'template_name': 'lib/password_change_done.html'}),

    # Сброс и восстановление пароля
    url(r'^password_reset/$',
        view=auth_views.password_reset,
        name='password_reset',
        kwargs={
            'template_name': 'lib/password_reset.html',
            'email_template_name': 'lib/password_reset_email.html',
            'post_reset_redirect': '/password_reset_done/',
            'password_reset_form': CustomPasswordResetForm,
        }),
    url(r'^password_reset_done/$',
       view=auth_views.password_reset_done,
       name='password_reset_done',
       kwargs={'template_name': 'lib/password_reset_done.html'}),
    url(r'^password_reset_confirm/(?P<uidb64>[0-9A-Za-z]{1,13})/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
       view=auth_views.password_reset_confirm,
       name='base_password_reset_confirm',
       kwargs={'template_name': 'lib/password_reset_confirm.html'}),
    url(r'^password_reset_complete/$',
       view=auth_views.password_reset_complete,
       name='password_reset_complete',
       kwargs={'template_name': 'lib/password_reset_complete.html'}),


    # Поставщиики данных для виджетов
    url(r'^forms_widget_autocomplete/', view='forms_widget_autocomplete',
       name='forms_widget_autocomplete'),

    url(r'^tree_widget/(?P<application>\w+)/(?P<model_name>\w+)/$',
       view='tree_widget', name='tree_widget'),

    # url(r'^autocomplete_widget/(?P<application>\w+)/(?P<model_name>\w+)/$',
    #     view=views.autocomplete_widget, name='autocomplete_widget'),

    # Документция по БД
    url(r'^documentation/$', view='db_documentation', name='db_documentation'),

    url(r'^set_lang/(?P<code>\w{2})/$', view='set_lang', name='set_lang'),

    # Скрипт закрытия модального окна и обновления opener
    # Для переадресации сюда по success_url
    url(r'^close_modal_window/$', view='close_modal_window', name='close_modal_window'),
    url(r'^close_modal_window_no_reload/$', view='close_modal_window_no_reload', name='close_modal_window_no_reload'),



)

oys/urls.py
# coding=utf-8

from django.conf.urls import patterns, include, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
                       # Библиотеки
                       url(r'^grappelli/', include('grappelli.urls')),
                       url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^i18n/', include('django.conf.urls.i18n', namespace='i18n')),

                       # Проект
                       url(r'^', include('common.urls', namespace='common')),
                       url(r'^lib/', include('lib.urls', namespace='lib')),
                       url(r'^account/', include('account.urls', namespace='account')),
                       url(r'^calculator/', include('calculator.urls', namespace='calculator')),
                       url(r'^sale/', include('sale.urls', namespace='sale')),
)

calculator/models.py
# coding=utf-8
import uuid
from django.conf import settings
from django.db import models
from django.utils.translation import ugettext_lazy as _
from calculator.constants import DELIVERY_INTERVALS, DELIVERY_REGION
from calculator.operations import GetClassifier


PERSON_GENDER_CHOICES = (
    (1, _('Male')),
    (2, _('Female')),
)

VEHICLE_TRANSIT_CHOICES = (
    (0, _('No')),
    (1, _('Yes')),
)

PAYMENT_TYPES = (
    ('cash', _('Cash')),
    ('epay', _('Online payment'))
)


def get_choices(name):
    if name:
        return [(obj.id, _(obj.title)) for obj in GetClassifier(name).execute()]

    return [('', '-' * 9)]


class ContractCalculationAbstract(models.Model):
    u"""
    Абстрактный класс с типовыми данными по договору
    """

    # Системные
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    client = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True, editable=False,
                               verbose_name=_('client'))
    d_create = models.DateTimeField(_('creation date'), auto_now_add=True, editable=False, db_index=True)
    # Признак того, что договор оформлен в калькуляторе до конца (проставляется при окончании процесса оформления
    # в калькуляторе)
    is_completed = models.BooleanField(_('completed'), default=False, editable=False, db_index=True)
    # Признак того, что договор выпущен на стороне брокера (должен проставляться извне)
    is_issued = models.BooleanField(_('issued'), default=False, editable=False, db_index=True)

    # Состояние интерфейса процесса
    step = models.CharField(_('calculator step'), max_length=50)
    substep = models.CharField(_('calculator sub step'), max_length=50)
    layer = models.CharField(_('calculator layer'), max_length=50)

    # Общие данные о текущем расчете, условия договора
    main_product = models.CharField(_('main product ID'), max_length=10, null=True, blank=True)
    main_product_text = models.CharField(_('main product title'), max_length=100, null=True, blank=True)

    # Условия страхования
    d_start = models.DateField(_('contract start date'), null=True, blank=True)
    term_insurance = models.PositiveSmallIntegerField(_('term insurance'), null=True, blank=True)

    # Страхователь
    ins_person_pin = models.CharField(_('PIN'), max_length=9, null=True, blank=True)
    ins_person_lname = models.CharField(_('last name'), max_length=50, null=True, blank=True)
    ins_person_fname = models.CharField(_('first name'), max_length=50, null=True, blank=True)
    ins_person_mname = models.CharField(_('middle name'), max_length=50, null=True, blank=True)
    ins_person_gender = models.PositiveSmallIntegerField(_('gender'), choices=PERSON_GENDER_CHOICES, default=1)
    ins_person_birthday = models.DateField(_('birthday'), null=True, blank=True)
    ins_country = models.PositiveIntegerField(_('country'), null=True, blank=True)

    ins_index = models.CharField(_('postal index (ZIP)'), max_length=6, null=True, blank=True)
    ins_city = models.PositiveIntegerField(_('city'), null=True, blank=True)
    ins_city_custom = models.CharField(_('city (custom)'), max_length=50, null=True, blank=True)
    ins_address = models.CharField(_('address'), max_length=70, null=True, blank=True)
    ins_street = models.CharField(_('street'), max_length=50, null=True, blank=True)
    ins_house = models.CharField(_('house'), max_length=10, null=True, blank=True)
    ins_apartment = models.CharField(_('apartment'), max_length=10, null=True, blank=True)
    ins_phone = models.CharField(_('phone'), max_length=12, null=True, blank=True)
    ins_email = models.EmailField(_('email'), null=True, blank=True)

    # Доставка и оплата
    delivery_type = models.CharField(_('delivery type'), max_length=10, null=True, blank=True)
    delivery_date = models.DateField(_('delivery date'), null=True, blank=True)
    delivery_time = models.IntegerField(_('delivery time interval'), null=True, blank=True, choices=DELIVERY_INTERVALS)
    delivery_city = models.PositiveIntegerField(_('city'), null=True, blank=True)
    delivery_region = models.CharField(_('region'), max_length=50, blank=True, null=True, choices=DELIVERY_REGION)
    delivery_street = models.CharField(_('street'), max_length=50, null=True, blank=True)
    delivery_house = models.CharField(_('house'), max_length=10, null=True, blank=True)
    delivery_apartment = models.CharField(_('apartment'), max_length=10, null=True, blank=True)
    delivery_phone = models.CharField(_('phone'), max_length=12, null=True, blank=True)
    delivery_comment = models.TextField(_('comments'), null=True, blank=True)
    delivery_takeout = models.IntegerField(_('takeout point'), null=True, blank=True)
    delivery_email = models.EmailField(_('delivery email'), null=True, blank=True)

    # Платежи
    payment_type = models.CharField(_('payment type'), max_length=10, null=True, blank=True, choices=PAYMENT_TYPES)
    s_premium = models.FloatField(null=True)

    # Онлайн-оплата
    d_payment = models.DateTimeField(null=True)
    s_payment = models.FloatField(null=True)

    class Meta:
        app_label = 'calculator'
        abstract = True


class VehicleContract(ContractCalculationAbstract):
    u"""
    Комплексный договор по страхованию ТС (ОСАГО, Уверенный водитель, Простое КАСКО)
    """

    # Общие данные о текущем расчете, условия договора
    p2_selected = models.BooleanField(_('product 2 selected'), default=False)
    p11_selected = models.BooleanField(_('product 11 selected'), default=False)
    p12_selected = models.BooleanField(_('product 12 selected'), default=False)
    p2_id = models.PositiveIntegerField(_('p2 document id'), null=True, blank=True)
    p11_id = models.PositiveIntegerField(_('p11 document id'), null=True, blank=True)
    p12_id = models.PositiveIntegerField(_('p12 document id'), null=True, blank=True)

    # Страхователь наследуется

    # Автомобиль
    auto_type = models.PositiveIntegerField(_('vehicle type'))
    auto_mark = models.PositiveIntegerField(_('vehicle mark'))
    auto_model = models.PositiveIntegerField(_('vehicle model'))
    auto_engine_capacity = models.PositiveIntegerField(_('vehicle engine capacity'), null=True, blank=True)
    auto_payload = models.PositiveIntegerField(_('vehicle payload'), null=True, blank=True)
    cnt_seats = models.PositiveIntegerField(_('vehicle seats'), null=True, blank=True)
    auto_createyear = models.PositiveIntegerField(_('vehicle creation year'), null=True, blank=True)
    auto_vin = models.CharField('VIN', max_length=17, null=True, blank=True)
    auto_engine = models.CharField('EIN', max_length=17, null=True, blank=True)
    auto_chassis = models.CharField('CIN', max_length=17, null=True, blank=True)
    auto_number = models.CharField(_('vehicle registration number'), max_length=12)
    auto_region = models.PositiveIntegerField(_('vehicle registration region'))
    auto_cost = models.PositiveIntegerField(_('vehicle cost'))

    # Продукт ОСАГО
    p2_inscompany = models.PositiveSmallIntegerField(_('insurance company'), null=True, blank=True)
    ateshgah_beshlik = models.BooleanField(_('ateshgah beshlik'), default=False)
    ateshgah_icbariplus = models.BooleanField(_('ateshgah icbariplus'), default=False)
    ateshgah_superkasko = models.BooleanField(_('ateshgah superkasko'), default=False)

    # Продукт Уверенный водитель
    p11_inscompany = models.PositiveSmallIntegerField(_('insurance company'), null=True, blank=True)
    p11_product_option = models.CharField(_('station selection'), max_length=50, null=True, blank=True)
    p11_beneficiary = models.CharField(_('beneficiary'), max_length=10, null=True, blank=True)
    p11_bank_beneficiary = models.PositiveSmallIntegerField(_('bank'), null=True, blank=True)

    # Продукт Простое КАСКО
    p12_inscompany = models.PositiveIntegerField(_('insurance company'), null=True, blank=True)
    p12_beneficiary = models.CharField(_('beneficiary'), max_length=10, null=True, blank=True)
    p12_bank_beneficiary = models.PositiveIntegerField(_('bank'), null=True, blank=True)
    insurance_coverage = models.PositiveIntegerField(_('insurance sum'), null=True, blank=True)
    accidents_quantity = models.PositiveIntegerField(_('accidents quantity'), null=True, blank=True)
    evacuation = models.BooleanField(_('evacuation'), default=False)
    cvi_extension_sum = models.PositiveIntegerField(_('cvi extension sum'), null=True, blank=True)
    accident_ins_sum = models.PositiveIntegerField(_('accident insurance sum'), null=True, blank=True)
    accident_ins_drivers = models.PositiveSmallIntegerField(_('accident insurance drivers'), null=True, blank=True)
    additional_drivers = models.BooleanField(_('additional drivers'), default=False)
    additional_driver_2 = models.BooleanField(_('second additional driver'), default=False)

    # Владелец ТС
    ins_owner = models.BooleanField(_('insurant is vehicle owner'), default=True)
    owner_pin = models.CharField(_('PIN'), max_length=9, null=True, blank=True)
    owner_lname = models.CharField(_('last name'), max_length=50, null=True, blank=True)
    owner_fname = models.CharField(_('first name'), max_length=50, null=True, blank=True)
    owner_mname = models.CharField(_('middle name'), max_length=50, null=True, blank=True)
    owner_gender = models.PositiveSmallIntegerField(_('gender'), null=True, blank=True, choices=PERSON_GENDER_CHOICES)
    owner_birthday = models.DateField(_('birthday'), null=True, blank=True)
    owner_country = models.PositiveIntegerField(_('country'), null=True, blank=True)
    owner_index = models.CharField(_('postal index (ZIP)'), max_length=6, null=True, blank=True)
    owner_city = models.PositiveIntegerField(_('city'), null=True, blank=True)
    owner_city_custom = models.CharField(_('city (custom)'), max_length=50, null=True, blank=True)
    owner_address = models.CharField(_('address'), max_length=70, null=True, blank=True)

calculator/templates/calculator/steps/vehicle/right_info.html
{% load i18n %}
<p class="b-info__phone">{% trans 'горячая линия' %} *0707</p>
<p class="b-info__sl">{% trans 'Ваш автомобиль' %}</p>
<p class="b-info__title"></p>
<p class="b-info__text"></p>
<a href="#" class="b-item__edit j-vehicle__edit">{% trans 'Редактировать' %}</a>

calculator/templates/calculator/steps/vehicle/step_3.html
{% load i18n %}
<div class="b-form__block n-form__insurance n-form__step clearfix" id="step-3">
    <div class="b-form__left clearfix">{# Место под контент #}</div>

    <div class="b-form__right clearfix">
        <div class="b-right__info j-right__info-fixed">
            {% include 'calculator/steps/vehicle/right_info.html' %}
        </div>
    </div>
</div>

calculator/templates/calculator/steps/vehicle/step_3_content.html
{% load i18n %}
<div>
    <a href="#" class="pull-right b-item__edit j-calculator__reset">{% trans 'В начало' %}</a>
</div>
<div class="b-step__title n-title__ico n-t-ico__car">
    <h2>{% trans 'Страховые продукты' %}</h2>
</div>
<div class="b-insurance__row">

    <div class="b-insurance__item">
        <div class="b-insurance__top">
            <h2 class="b-insurance__title"><a href="#">{{ p2.title }}</a></h2>

            <p class="b-insurance__info">{{ p2.description }}</p>
        </div>
        <div class="b-insurance__btm">
            <p class="b-insurance__price">{{ p2.price|floatformat:"2" }} <span>AZN</span></p>
            <a href="#" class="order button insurance_product__btn j-next__click"
               data-product-id="{{ p2.id }}" data-product-title="{{ p2.title }}" data-product-price="{{ p2.price|floatformat:"2" }}">{% trans 'выбрать' %}</a>
        </div>
    </div>

    {% if p11 %}
    <div class="b-insurance__item n-ins__pad">
        <div class="b-insurance__top">
            <h2 class="b-insurance__title"><a href="#">{{ p11.title }}</a></h2>

            <p class="b-insurance__info">{{ p11.description }}</p>
        </div>
        <div class="b-insurance__btm">
            <p class="b-insurance__price">{{ p11.price|floatformat:"2" }} <span>AZN</span></p>
            <a href="#" class="order button insurance_product__btn j-next__click"
               data-product-id="{{ p11.id }}" data-product-title="{{ p11.title }}" data-product-price="{{ p11.price|floatformat:"2" }}">{% trans 'выбрать' %}</a>
        </div>
    </div>
    {% endif %}

</div>

<div class="b-insurance__row">
    {% if p12 %}
    <div class="b-insurance__item">
        <div class="b-insurance__top">
            <h2 class="b-insurance__title"><a href="#">{{ p12.title }}</a></h2>

            <p class="b-insurance__info">{{ p12.description }}</p>
        </div>
        <div class="b-insurance__btm">
            <p class="b-insurance__price">{{ p12.price|floatformat:"2" }} <span>AZN</span></p>
            <a href="#" class="order button insurance_product__btn j-next__click"
               data-product-id="{{ p12.id }}" data-product-title="{{ p12.title }}" data-product-price="{{ p12.price|floatformat:"2" }}">{% trans 'выбрать' %}</a>
        </div>
    </div>
    {% endif %}
</div>

<div id="product_preload_block">
<div id="p2_preloaded" style="display: none"><table>{{ p2_preload|safe }}</table></div>
<div id="p11_preloaded" style="display: none"><table>{{ p11_preload|safe }}</table></div>
<div id="p12_preloaded" style="display: none"><table>{{ p12_preload|safe }}</table></div>
</div>

calculator/templates/calculator/steps/vehicle/step_4_options_2.html
{% load i18n %}

<div class="b-data__line clearfix">
    <div class="b-data__wr">
        <input type="checkbox" name="p2_selected" id="id_p2_selected" class="b-form__input">
        <label for="id_p2_selected">{% trans 'ОСАГО' %}</label>

        {# Help block #}
        {% trans 'Обязательное страхование ответственности автовладельцев перед 3-ми лицами' as fin_help %}
        {% include 'calculator/question.html' with answ=fin_help %}
    </div>
</div>

calculator/templates/calculator/steps/vehicle/step_5.html
{% load i18n %}
<div class="b-form__block n-form__despolicy n-form__step clearfix" id="step-5">
    <div class="b-form__left clearfix">
        <div>
            <a href="#" class="pull-right b-item__edit j-calculator__reset">{% trans 'В начало' %}</a>
        </div>
        <div class="b-step__title n-title__ico n-t-ico__car">
            <h2>{% trans 'Оформление полиса' %}</h2>
        </div>

        {# Полоса прогресса заполнения формы (точки) #}
        <ul class="b-step__current">
            <li class="b-step__current-item n-item__curr"><a href="#"></a></li>
            <li class="b-step__current-item"><a href="#"></a></li>
            <li class="b-step__current-item"><a href="#"></a></li>
            <li class="b-step__current-item"><a href="#"></a></li>
            <li class="b-step__current-item"><a href="#"></a></li>
        </ul>

        {# Использование данных личного кабинета (временно отключено, до появления личного кабинета) #}
{#        <div class="b-data__line">#}
{#            <div class="b-data__wr n-wr__green">#}
{#                <p>{% trans 'Использовать данные из личного кабинета' %}</p>#}
{#                <div class="row">#}
{#                    <div class="b-data__wr col-xs-6">#}
{#                        <input type="radio" data-window="1" name="calc[savedata]" id="calc[savedata][no]"#}
{#                               class="b-form__radio n-main__radio n-savedata__no">#}
{#                        <label for="calc[savedata][no]">{% trans 'Нет' %}</label>#}
{#                    </div>#}
{#                    <div class="b-data__wr col-xs-6">#}
{#                        <input type="radio" data-window="1" name="calc[savedata]" id="calc[savedata][yes]"#}
{#                               class="b-form__radio n-main__radio n-savedata__yes">#}
{#                        <label for="calc[savedata][yes]">{% trans 'Да' %}</label>#}
{#                    </div>#}
{#                </div>#}
{#            </div>#}
{#        </div>#}

        {# Данные о ТС #}
        <div class="b-calc__item n-calc__vehicle n-form__layer e-active clearfix" id="layer-1" style="display: block">
            <h3>{% trans 'Транспортное средство' %}</h3>

            <div class="b-layer__content">

                {# Поле VIN #}
                <div class="b-data__line">
                    <div class="b-label__wr col-md-4 col-xs-5">
                        <div class="row"><label for="id_auto_vin">VIN</label></div>
                    </div>
                    <div class="b-input__wr col-md-7 col-xs-6">
                        <div class="row">
                            <input type="text" name="auto_vin" id="id_auto_vin" class="b-input">
                        </div>
                    </div>

                    {% trans 'Vehicle identification number — уникальный код транспортного средства, состоящий из 17 символов' as vin_help %}
                    {% include 'calculator/question.html' with answ=vin_help %}

                    <div class="field-error"><span></span></div>
                </div>

                {# Поле Номер двигателя #}
                <div class="b-data__line">
                    <div class="b-label__wr col-md-4 col-xs-5">
                        <div class="row">
                            <label for="id_auto_engine">{% trans 'Номер двигателя' %}</label>
                        </div>
                    </div>
                    <div class="b-input__wr col-md-7 col-xs-6">
                        <div class="row">
                            <input type="text" name="auto_engine" id="id_auto_engine" class="b-input">
                        </div>
                    </div>
                    <div class="field-error"><span></span></div>
                </div>

                {# Поле Номер кузова #}
                <div class="b-data__line">
                    <div class="b-label__wr col-md-4 col-xs-5">
                        <div class="row">
                            <label for="id_auto_chassis">{% trans 'Номер кузова' %}</label>
                        </div>
                    </div>
                    <div class="b-input__wr col-md-7 col-xs-6">
                        <div class="row">
                            <input type="text" name="auto_chassis" id="id_auto_chassis" class="b-input">
                        </div>
                    </div>
                    <div class="field-error"><span></span></div>
                </div>

                {# Поле Регистрационный номер ТС #}
                <div class="b-data__line">
                    <div class="b-label__wr col-md-4 col-xs-5">
                        <div class="row">
                            <label for="id_auto_number">{% trans 'Регистрационный<br/>номер ТС' %}</label>
                        </div>
                    </div>
                    <div class="b-input__wr col-md-7 col-xs-6">
                        <div class="row">
                            <input type="text" name="auto_number" id="id_auto_number" class="b-input">
                        </div>
                    </div>
                    <div class="field-error"><span></span></div>
                </div>

                {# Поле Регион регистрации #}
                {% trans 'Регион регистрации' as reg_region_tr %}
                {% trans 'Регион, в котором ТС зарегистрировано' as reg_region_help %}
                {% include 'calculator/steps/g_selection_field.html' with field_name='auto_region' field_label=reg_region_tr help_text=reg_region_help objects=auto_regions %}

                <a href="#" class="order button j-next__layer">{% trans 'Продолжить' %}</a>
            </div>
        </div>

        {# Данные о договоре страхования TODO: #}
        <div class="b-calc__item n-calc__insurance n-form__layer clearfix" id="layer-2">
            <h3>{% trans 'Условия страхования' %}</h3>

            <div class="b-layer__content">

                {# Дата начала действия договора #}
                <div class="b-data__line">
                    <div class="b-label__wr col-md-4 col-xs-5">
                        <div class="row">
                            <label for="id_d_start">{% trans 'Дата начала договора' %}</label>
                        </div>
                    </div>
                    <div class="b-input__wr col-md-7 col-xs-6">
                        <div class="row">
                            <input type="text" name="d_start" id="id_d_start" class="b-input j-dog__from n-calendar">
                        </div>
                    </div>

                    {% trans 'Дата, с которой договор страхования вступает в силу' as d_start_help %}
                    {% include 'calculator/question.html' with answ=d_start_help %}

                    <div class="field-error"><span></span></div>
                </div>

                {# Срок страхования #}
                <div class="b-data__line">
                    <div class="b-label__wr col-md-4 col-xs-5">
                        <div class="row">
                            <label for="id_term_insurance">{% trans 'Срок страхования' %}</label>
                        </div>
                    </div>
                    <div class="b-input__wr col-md-7 col-xs-6">
                        <div class="row n-insurance__term">
                            <select name="term_insurance" id="id_term_insurance" class="b-select">
                                <option value="1">{% trans '12 месяцев' %}</option>
                            </select>
                        </div>
                    </div>

                    {% trans 'Срок, в течение которого договор страхования будет действовать' as termn_ins_help %}
                    {% include 'calculator/question.html' with answ=termn_ins_help %}

                    <div class="field-error"><span></span></div>
                </div>

                <a href="#" class="order button j-next__layer">{% trans 'Продолжить' %}</a>
            </div>
        </div>

        {# Данные о страхователе #}
        <div class="b-calc__item n-calc__insurer n-form__layer clearfix" id="layer-3">
            <h3>{% trans 'Страхователь' %}</h3>

            <div class="b-layer__content">

                {% include 'calculator/steps/vehicle/step_5_person_info.html' with fields=ins_fields %}

                <a href="#" class="order button j-next__layer">{% trans 'Продолжить' %}</a>

            </div>
        </div>

        {# Данные о владельце #}
        <div class="b-calc__item n-calc__insurer n-form__layer clearfix" id="layer-4">
            <h3>{% trans 'Владелец ТС' %}</h3>

            <div class="b-layer__content">

                <div class="b-data__line">
                    <div class="b-data__wr">
                        <input type="checkbox" name="ins_owner" id="id_ins_owner" class="b-form__input" checked>
                        <label for="id_ins_owner">{% trans 'Страхователь - владелец ТС' %}</label>
                    </div>
                </div>

                <div id="ins_owner_fields" style="display: none;">
                {% include 'calculator/steps/vehicle/step_5_person_info.html' with fields=owner_fields %}
                </div>

                <a href="#" class="order button j-next__layer">{% trans 'Продолжить' %}</a>

            </div>
        </div>

        {# Данные о дополнительных водителях #}
        <div class="b-calc__item n-calc__insurer n-form__layer clearfix" id="layer-5">
            <h3>{% trans 'Дополнительные водители' %}</h3>

            <div class="b-layer__content">

                {% include 'calculator/steps/vehicle/step_5_person_info.html' with fields=ad1_fields %}

                <div class="b-data__line">
                    <div class="b-data__wr">
                        <input type="checkbox" name="additional_driver_2" id="id_additional_driver_2" class="b-form__input">
                        <label for="id_additional_driver_2">{% trans 'Есть еще один дополнительный водитель' %}</label>
                    </div>
                </div>

                <div id="additional_driver_2_fields" style="display: none">
                    {% include 'calculator/steps/vehicle/step_5_person_info.html' with fields=ad2_fields %}
                </div>

                <a href="#" class="order button j-next__layer">{% trans 'Продолжить' %}</a>

            </div>
        </div>

    </div>

    <div class="b-form__right clearfix">
        <div class="b-right__info j-right__info-fixed">
            {# Информация о ТС #}
            {% include 'calculator/steps/vehicle/right_info.html' %}
            {# Выбранные продукты #}
            {% include 'calculator/steps/vehicle/right_products.html' %}

            <button type="button" class="order button j-last__show j-next__click">{% trans 'Оформить' %}</button>

        </div>
    </div>

</div>