common/urls.py
# coding=utf-8

from django.conf.urls import patterns, url
from django.contrib.auth import views as auth_views

from common import views

urlpatterns = patterns('common.views',

                       # Перезвоните мне
                       url(r'^call_me_handler/$', view=views.CallMeHandlerView.as_view(), name='call_me_handler'),
                       url(r'^ask_question/$', view=views.QuestionProcessView.as_view(), name='ask_question'),
                       url(r'^make_complaint/$', view=views.ComplaintProcessView.as_view(), name='make_complaint'),

                       # url(r'^logout/$',
                       #     view=auth_views.logout,
                       #     name='logout',
                       #     kwargs={'template_name': 'account/auth/logout.html'}),
)

lib/urls.py
# coding=utf-8

from django.conf.urls import patterns, url
from django.contrib.auth import views as auth_views
from .forms import CustomPasswordResetForm

urlpatterns = patterns(
    'lib.views',

    # Управление учетными записями
    url(r'^login/$',
       view=auth_views.login,
       name='login',
       kwargs={'template_name': 'lib/login.html'}),
    url(r'^logout/$',
       view=auth_views.logout,
       name='logout',
       kwargs={'template_name': 'lib/logout.html'}),

    # Смена пароля
    url(r'^password_change/$', view=auth_views.password_change,
       name='password_change',
       kwargs={'template_name': 'lib/password_change.html',
               'post_change_redirect': '/password_change_done/'}),
    url(r'^password_change_done/$',
       view=auth_views.password_change_done,
       name='password_change_done',
       kwargs={'template_name': 'lib/password_change_done.html'}),

    # Сброс и восстановление пароля
    url(r'^password_reset/$',
        view=auth_views.password_reset,
        name='password_reset',
        kwargs={
            'template_name': 'lib/password_reset.html',
            'email_template_name': 'lib/password_reset_email.html',
            'post_reset_redirect': '/password_reset_done/',
            'password_reset_form': CustomPasswordResetForm,
        }),
    url(r'^password_reset_done/$',
       view=auth_views.password_reset_done,
       name='password_reset_done',
       kwargs={'template_name': 'lib/password_reset_done.html'}),
    url(r'^password_reset_confirm/(?P<uidb64>[0-9A-Za-z]{1,13})/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
       view=auth_views.password_reset_confirm,
       name='base_password_reset_confirm',
       kwargs={'template_name': 'lib/password_reset_confirm.html'}),
    url(r'^password_reset_complete/$',
       view=auth_views.password_reset_complete,
       name='password_reset_complete',
       kwargs={'template_name': 'lib/password_reset_complete.html'}),


    # Поставщиики данных для виджетов
    url(r'^forms_widget_autocomplete/', view='forms_widget_autocomplete',
       name='forms_widget_autocomplete'),

    url(r'^tree_widget/(?P<application>\w+)/(?P<model_name>\w+)/$',
       view='tree_widget', name='tree_widget'),

    # url(r'^autocomplete_widget/(?P<application>\w+)/(?P<model_name>\w+)/$',
    #     view=views.autocomplete_widget, name='autocomplete_widget'),

    # Документция по БД
    url(r'^documentation/$', view='db_documentation', name='db_documentation'),

    url(r'^set_lang/(?P<code>\w{2})/$', view='set_lang', name='set_lang'),

    # Скрипт закрытия модального окна и обновления opener
    # Для переадресации сюда по success_url
    url(r'^close_modal_window/$', view='close_modal_window', name='close_modal_window'),
    url(r'^close_modal_window_no_reload/$', view='close_modal_window_no_reload', name='close_modal_window_no_reload'),



)

oys/urls.py
# coding=utf-8

from django.conf.urls import patterns, include, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
                       # Библиотеки
                       url(r'^grappelli/', include('grappelli.urls')),
                       url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^i18n/', include('django.conf.urls.i18n', namespace='i18n')),

                       # Проект
                       url(r'^', include('common.urls', namespace='common')),
                       url(r'^lib/', include('lib.urls', namespace='lib')),
                       url(r'^account/', include('account.urls', namespace='account')),
                       url(r'^calculator/', include('calculator.urls', namespace='calculator')),
                       url(r'^sale/', include('sale.urls', namespace='sale')),
)

common/models.py
# coding=utf-8

from django.db import models
from django.utils.translation import ugettext_lazy as _


CALLME_REASON = (
    (1, _(u'Купить страховку')),
    (2, _(u'Обсудить условия')),
    (3, _(u'Прочее')),
)

RESPONSE_TYPE = (
    ('mobile', _(u'Мобильным телефоном')),
    ('email', _(u'Электронной почтой')),
)


class CallMe(models.Model):
    u""" Обращения для обратного звонка """

    d_create = models.DateTimeField(auto_now_add=True, verbose_name=_(u'Дата создания'))
    name = models.CharField(max_length=50, verbose_name=_(u'Имя'))
    phone = models.CharField(max_length=50, verbose_name=_(u'Телефон'))
    d_call = models.DateField(verbose_name=_(u'Дата звонка'))
    d_call_from = models.TimeField(verbose_name=_(u'Время с'))
    d_call_to = models.TimeField(verbose_name=_(u'Время до'))
    reason = models.PositiveSmallIntegerField(choices=CALLME_REASON, verbose_name=_(u'Тема звонка'))

common/forms.py
# coding=utf-8

from django import forms
from django.utils.translation import ugettext_lazy as _

from common.models import CALLME_REASON, RESPONSE_TYPE


class CallMeForm(forms.Form):
    u""" Форма обратной связи """
    name = forms.CharField()
    phone = forms.CharField()
    d_call = forms.DateField()
    d_call_from = forms.TimeField()
    d_call_to = forms.TimeField()
    reason = forms.TypedChoiceField(coerce=int, choices=CALLME_REASON)
    next_url = forms.CharField()


class QuestionForm(forms.Form):
    u""" Форма обратной связи """
    question = forms.CharField()
    last_name = forms.CharField(required=False)
    first_name = forms.CharField()
    middle_name = forms.CharField(required=False)
    phone = forms.CharField(required=False)
    email = forms.EmailField()
    response_type = forms.TypedChoiceField(coerce=str, choices=RESPONSE_TYPE)


class ComplaintForm(forms.Form):
    u""" Форма обратной связи """
    complaint = forms.CharField()
    last_name = forms.CharField(required=False)
    first_name = forms.CharField()
    middle_name = forms.CharField(required=False)
    phone = forms.CharField(required=False)
    email = forms.EmailField()
    response_type = forms.TypedChoiceField(coerce=str, choices=RESPONSE_TYPE)

common/views.py
# coding=utf-8

from django.template.loader import render_to_string
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.utils.translation import ugettext as _
from django.conf import settings
from lib.utils import send_mail
from django.views.generic import FormView


from common import models, forms


class CallMeHandlerView(FormView):
    u"""
    Обработка формы обратного звонка.
    Сохраним в обращение и отправим письмо
    """
    form_class = forms.CallMeForm

    def form_valid(self, form):
        data = form.cleaned_data

        req = models.CallMe(name=data['name'],
                            phone=data['phone'],
                            d_call=data['d_call'],
                            d_call_from=data['d_call_from'],
                            d_call_to=data['d_call_to'],
                            reason=data['reason'])
        req.save()

        send_mail(u'Позвоните мне',
                  render_to_string('common/email/call_me.html', {'call_request': req}),
                  settings.MANAGERS)

        messages.success(self.request, _(u'Request sent. expect an answer'))

        return HttpResponseRedirect(self.request.POST['next_url'])

    def form_invalid(self, form):
        messages.error(self.request, _(u'Request not sent: %(error_message)s') % {'error_message': form.errors})
        return HttpResponseRedirect(self.request.POST['next_url'])


class QuestionProcessView(FormView):
    u"""
    Обработать вопрос из формы обратной связи
    """
    form_class = forms.QuestionForm

    def form_valid(self, form):
        send_mail(u'Задан вопрос на сайте',
                  render_to_string('common/email/question.html', form.cleaned_data),
                  settings.MANAGERS)
        messages.success(self.request, _(u'Request sent. expect an answer'))

        return HttpResponseRedirect(self.request.POST['next_url'])

    def form_invalid(self, form):
        messages.error(self.request, _(u'Request not sent: %(error_message)s') % {'error_message': form.errors})
        return HttpResponseRedirect(self.request.POST['next_url'])


class ComplaintProcessView(FormView):
    u"""
    Обработать жалобу из формы обратной связи
    """
    form_class = forms.ComplaintForm

    def form_valid(self, form):
        send_mail(u'Создана жалоба на сайте',
                  render_to_string('common/email/complaint.html', form.cleaned_data),
                  settings.MANAGERS)
        messages.success(self.request, _(u'Request sent. expect an answer'))

        return HttpResponseRedirect(self.request.POST['next_url'])

    def form_invalid(self, form):
        messages.error(self.request, _(u'Request not sent: %(error_message)s') % {'error_message': form.errors})
        return HttpResponseRedirect(self.request.POST['next_url'])

common/templates/common/base.html
{% load i18n %}
{% load staticfiles %}
{% load static %}

{% get_current_language as LANGUAGE_CODE %}
{% get_available_languages as LANGUAGES %}

<!DOCTYPE html>
<html lang="ru-RU">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>OYSB</title>

    {% block css %}
        <link rel="stylesheet" href="http://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
        <link rel="stylesheet" type="text/css" href="{% static "common/css/ui.customization.css" %}">
        <link rel="stylesheet" type="text/css" href="{% static "common/css/inputs.css" %}">
        <link rel="stylesheet" type="text/css" href="{% static "common/css/fonts.css" %}">
        <link rel="stylesheet" type="text/css" href="{% static "common/css/bootstrap.min.css" %}">
        <link rel="stylesheet" type="text/css" href="{% static "common/css/bootstrap-theme.min.css" %}">
        <link rel="stylesheet" type="text/css" href="{% static "common/css/superslides.css" %}">
        <link rel="stylesheet" type="text/css" href="{% static "common/js/slick/slick.css" %}">
        <link rel="stylesheet" type="text/css" href="{% static "common/css/jquery.rollbar.css" %}">
        <link rel="stylesheet" type="text/css" href="{% static "common/css/jquery.jscrollpane.css" %}">
        <link rel="stylesheet" type="text/css" href="{% static "common/css/jquery.confirm.css" %}">
        <link rel="stylesheet" type="text/css" href="{% static "common/css/jClever.css" %}">
        <link rel="stylesheet" type="text/css" href="{% static "common/css/contacts-style.css" %}">
        <link rel="stylesheet" type="text/css" href="{% static "common/css/style.css" %}">
        <link rel="stylesheet" type="text/css" href="{% static "common/style.css" %}">

        <link rel="stylesheet" type="text/css" href="{% static "common/js/videojs/video-js.min.css" %}">

        <link rel="stylesheet" type="text/css" href="{% static "calculator/css/calculator.css" %}">
        <link rel="stylesheet" type="text/css" href="{% static "calculator/css/calculator-add.css" %}">
        <!-- NEW HTML START -->
				<link rel="stylesheet" type="text/css" href="{% static "sale/css/sale.css" %}">
				<!-- NEW HTML END -->
    {% endblock css %}

    <script>
        var current_path = '{{request.path}}'
    </script>

</head>

<body>

    <!-- Yandex.Metrika counter -->
<script type="text/javascript">
    (function (d, w, c) {
        (w[c] = w[c] || []).push(function() {
            try {
                w.yaCounter36790000 = new Ya.Metrika({
                    id:36790000,
                    clickmap:true,
                    trackLinks:true,
                    accurateTrackBounce:true,
                    webvisor:true
                });
            } catch(e) { }
        });

        var n = d.getElementsByTagName("script")[0],
            s = d.createElement("script"),
            f = function () { n.parentNode.insertBefore(s, n); };
        s.type = "text/javascript";
        s.async = true;
        s.src = "https://mc.yandex.ru/metrika/watch.js";

        if (w.opera == "[object Opera]") {
            d.addEventListener("DOMContentLoaded", f, false);
        } else { f(); }
    })(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/36790000" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->

{% if messages %}
<div id="confirmOverlay" style="">
    <div id="confirmBox">
        <p class="confirmTitle">{% trans 'Внимание' %}</p>
        <a href="" class="confirmClose"></a>
        <p>
            {% for message in messages %}{{ message|safe }}{% if not forloop.last %}<br/>{% endif %}{% endfor %}
        </p>
        <div id="confirmButtons" class="clearfix">
            <a href="#" class="button order confirm-btn confirm-yes" onclick="$(this).parents('#confirmOverlay').remove()">OK</a>
        </div>
    </div>
</div>
{% endif %}


{# Панель навигации #}
{% block header %}
    {% include 'common/includes/base_header.html' %}
{% endblock header %}


{# Контент должен быть тут #}
{% block body_content %}{% endblock %}


{# Подвал #}
<footer class="page-footer">
    <div class="container-fluid">
        <div class="row footer-menu foot-1">
            <div class="col-xs-1 "></div>
            <div class="col-md-3 col-sm-4 col-xs-11">
                <div class="foot-l">
                    <h3>{% trans 'Страхование' %}</h3>
                    <ul>
                        <li><a href="/insurance/"><p>{% trans 'Все страховые продукты' %}</p></a></li>
                        <li><a href="/insurance/auto/"><p>{% trans 'Страхование автомобиля' %}</p></a></li>
                        <li><a href="/insurance/property/"><p>{% trans 'Страхование недвижимости' %}</p></a></li>
                        <li><a href="/insurance/health/"><p>{% trans 'Страхование здоровья' %}</p></a></li>
                        <li><a href="/insurance/travel/"><p>{% trans 'Страхование путешествий' %}</p></a></li>
                    </ul>
                </div>
            </div>
            <div class="col-xs-1 visible-xs"></div>
            <div class="col-md-4 col-sm-4 col-xs-11">
{#                <div class="foot-c">#}
{#                    <h3>{% trans 'Банковские услуги' %}</h3>#}
{#                    <ul>#}
{#                        <li><a href="#"><p>{% trans 'Кредитование для физических лиц' %}</p></a></li>#}
{#                        <li><a href="#"><p>{% trans 'Вклады' %}</p></a></li>#}
{#                    </ul>#}
{#                </div>#}
            </div>
            <div class="col-xs-1"></div>
            <div class="col-md-3 col-sm-2  col-xs-11">
                <div class="foot-r">
                    <h3>{% trans 'Компания' %}</h3>
                    <ul>
                        <li><a href="/about/"><p>{% trans 'О компании' %}</p></a></li>
                        <li><a href="/partners/"><p>{% trans 'Партнеры' %}</p></a></li>
                        <li><a href="/faq/"><p>{% trans 'Вопросы и ответы' %}</p></a></li>
                        <li><a href="/contacts/"><p>{% trans 'Контакты' %}</p></a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="row footer-menu foot-2">
            <div class="col-xs-1"></div>
            <div class="col-sm-3 col-xs-11">
                <div class="foot-l">
                    <h3>{% trans 'Язык' %}</h3>

                    <div class="lang">
                        {% for lang_code, lang_name in LANGUAGES %}
                            <a {% if lang_code == LANGUAGE_CODE %}class="active"{% endif %}
                               href="{% url 'lib:set_lang' code=lang_code %}?back_url={{request.path}}">
                                <p>&nbsp; {{lang_code|upper}} &nbsp;</p>
                            </a>
                            {% if not forloop.last %}
                                <p>&#8260;&nbsp;</p>
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="col-xs-1 visible-sm visible-xs"></div>
            <div class="col-sm-4 col-xs-10">
                <div class="foot-c foot-center">
                    <a href="#" data-toggle="modal" data-backdrop="false" data-target=".callback">
                        <span class="text-nowrap" style="font-size: 37px">*0707</span>
                    </a>
                    <a href="#" data-toggle="modal" data-backdrop="false" data-target=".question_show_modal" class="button">
                        {% trans 'Задайте вопрос' %}
                    </a>
                </div>
            </div>
            <div class="clearfix visible-xs-block"></div>
            <div class="col-xs-1"></div>
            <div class="col-sm-2 col-xs-11">
                <div class="foot-r">
                    <h3>{% trans 'Контакты' %}</h3>

                    <p><a href="mailto:info@oys.az">info@oys.az</a></p>
{#                    <p>{% trans 'AZ1025 Баку,<br/>Ахмед Раджабли 31/5, Aztex Plaza<br/>Азербайджан' %}</p>#}
                </div>
            </div>
        </div>
        <div class="clearfix visible-xs-block"></div>
        <div class="row">
            <div class="col-sm-3 col-xs-1"></div>
            <div class="col-sm-6 col-xs-10">
                <div class="list row">
                    <div class="btn-group" role="toolbar" aria-label="...">
                        <a href="https://www.facebook.com/oysaz"><img src="{% static "common/img/icon_01.png" %}"></a>
                        <a href="#"><img src="{% static "common/img/icon_03.png" %}"></a>
                        {# <a href="#"><img src="{{ STATIC_URL }}common/img/icon_05.png"></a> #}
                        {# <a href="#"><img src="{{ STATIC_URL }}common/img/icon_07.png"></a>#}
                        <a href="#"><img src="{% static "common/img/icon_09.png" %}"></a>
                    </div>
                </div>
                <p class="pol">© 2015 «Odlar Yurdu Sığorta brokeri». {% trans 'Лицензия С № 080624 от 05 ноября 2014 года' %}</p>
            </div>
        </div>
    </div>
</footer>

{# Фиксированная панель (боковая панель, с иконками для вызова модалок) #}
{#{% include 'common/includes/base_modal_icons.html' %}#}

{# Модальные окна #}
{# Чат #}
{#{% include 'common/modals/chat.html' %}#}

{# Мои расчеты #}
{#{% include 'common/modals/calc.html' %}#}

{# Feed #}
{#{% include 'common/modals/feed.html' %}#}


{# Обратный звонок #}
{% include 'common/modals/callback.html' %}

{# Задать вопрос (модальное окно) #}
{% include 'common/modals/question.html' %}

{# Модальное окно калькулятора (!!! не забудь стили и скрипты раскомментить) #}
{% include 'calculator/calculator_modal.html' %}

{# Вход #}
{#{% include 'common/modals/login.html' %}#}

{# Маленькая всплывашка с уникальным банковским предложением#}
{#{% include 'common/modals/bank_offer.html' %}#}

{# Выор языка #}
{% include 'common/modals/lang.html' %}

{% block js %}
    <script src="{% static "common/js/jquery-1.11.2.min.js" %}"></script>
    <script src="{% static "common/js/jquery.mousewheel.js" %}"></script>
    <script src="{% static "common/js/jquery.maskedinput.min.js" %}"></script>
    <script src="{% static "common/js/jquery.rollbar.min.js" %}"></script>
    <script src="{% static "common/js/jquery.jscrollpane.min.js" %}"></script>
    <script src="{% static "common/js/jquery.superslides.min.js" %}"></script>
    <script src="{% static "common/js/jquery.confirm.js" %}"></script>
    <script src="{% static "common/js/jquery-ui.min.js" %}"></script>
    <script src="{% static "common/js/jClever.min.js" %}"></script>
    <script src="{% static "common/js/md5.js" %}"></script>
    <script src="{% static "common/js/script.js" %}"></script>
    <script src="{% static "common/js/bootstrap.min.js" %}"></script>
    <script src="{% static "common/js/slick/slick.min.js" %}"></script>
    <script src="{% static "common/js/jquery.x-tools.js" %}"></script>
    <script src="{% static "common/js/underscore-min.js" %}"></script>


    <script type="text/javascript">
        var currLng = '{{ LANGUAGE_CODE }}';
        var requestGet = {
            {% for k, v in request.GET.items %}{{ k }}: '{{ v }}'{% endfor %}
        };
    </script>

    <script src="{% static "common/js/moment.min.js" %}"></script>
    <script src="{% static "common/js/moment-range.min.js" %}"></script>
    <script src="{% static "common/js/js.cookie.js" %}"></script>
    <script src="{% static "common/js/videojs/video.js" %}"></script>
    <script>videojs.options.flash.swf = "{% static "common/js/videojs/video-js.swf" %}"</script>

    <script src="{% static "common/js/i18next-1.9.0.min.js" %}"></script>
    <script src="{% static "common/js/form-validator/jquery.form-validator.min.js" %}"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA9OW6Sl5MPFzgiRLjA7lujc4wpRj5Qgws&amp;sensor=false"></script>

    <script src="{% static "calculator/js/workflow.js" %}"></script>
    <script src="{% static "calculator/js/calculator.js" %}"></script>
    <script src="{% static "calculator/js/vehicle_calculator.js" %}"></script>
    <script src="{% static "calculator/js/property_calculator.js" %}"></script>
    <script src="{% static "calculator/js/travel_calculator.js" %}"></script>
    <script src="{% static "calculator/js/health_calculator.js" %}"></script>
    <script src="{% static "calculator/js/online_payment.js" %}"></script>

    <script src="{% static "lib/script.js" %}"></script>

    <script src="{% static "common/script.js" %}"></script>
    <script src="{% static "common/utils.js" %}"></script>
    <script src="{% static "account/script.js" %}"></script>
    <script src="{% static "sale/js/sale.js" %}"></script>




{% endblock %}
{% block sale_js %}

    {% endblock %}
<div class="splash-box-fix" style="background-color: rgba(0, 0, 0, 0.85);">
    <a href="#" class="splash-box-close"></a>
    <div class="splash-video-container"></div>
</div>
<div class="compare-box-fix">
    <a href="#" class="compare-box-close"></a>
    <div class="splash-compare-container"></div>
</div>
</body>
</html>

common/templates/common/inner.html
{% extends 'common/base.html' %}

{% block header %}
    {% include 'common/includes/inner_header.html' %}
{% endblock header %}

{% block body_content %}{% endblock body_content %}
{% block sale_js %}
{% endblock %}