calculator/urls.py
# coding=utf-8
from django.conf.urls import patterns, url
from .views import ajax_calculator_reset, VehicleProductCalculator, PropertyProductCalculator, TravelProductCalculator, \
    HealthProductCalculator, OnlinePaymentFormView, check_payment



urlpatterns = patterns(
    '',
    url(r'^modal/$', view=ajax_calculator_reset, name='general_product_calculator'),
    url(r'^modal/vehicle/$', view=VehicleProductCalculator.as_view(), name='vehicle_product_calculator'),
    url(r'^modal/property/$', view=PropertyProductCalculator.as_view(), name='property_product_calculator'),
    url(r'^modal/travel/$', view=TravelProductCalculator.as_view(), name='travel_product_calculator'),
    url(r'^modal/health/$', view=HealthProductCalculator.as_view(), name='health_product_calculator'),

    # online-оплата
    url(r'^online_payment_form/$', view=OnlinePaymentFormView.as_view(), name='online_payment_form'),
    url(r'^check_payment/(?P<product>(vehicle))/(?P<key>[0-9A-Za-z-]{36})/$', view=check_payment, name='check_payment'),
)

lib/urls.py
# coding=utf-8

from django.conf.urls import patterns, url
from django.contrib.auth import views as auth_views
from .forms import CustomPasswordResetForm

urlpatterns = patterns(
    'lib.views',

    # Управление учетными записями
    url(r'^login/$',
       view=auth_views.login,
       name='login',
       kwargs={'template_name': 'lib/login.html'}),
    url(r'^logout/$',
       view=auth_views.logout,
       name='logout',
       kwargs={'template_name': 'lib/logout.html'}),

    # Смена пароля
    url(r'^password_change/$', view=auth_views.password_change,
       name='password_change',
       kwargs={'template_name': 'lib/password_change.html',
               'post_change_redirect': '/password_change_done/'}),
    url(r'^password_change_done/$',
       view=auth_views.password_change_done,
       name='password_change_done',
       kwargs={'template_name': 'lib/password_change_done.html'}),

    # Сброс и восстановление пароля
    url(r'^password_reset/$',
        view=auth_views.password_reset,
        name='password_reset',
        kwargs={
            'template_name': 'lib/password_reset.html',
            'email_template_name': 'lib/password_reset_email.html',
            'post_reset_redirect': '/password_reset_done/',
            'password_reset_form': CustomPasswordResetForm,
        }),
    url(r'^password_reset_done/$',
       view=auth_views.password_reset_done,
       name='password_reset_done',
       kwargs={'template_name': 'lib/password_reset_done.html'}),
    url(r'^password_reset_confirm/(?P<uidb64>[0-9A-Za-z]{1,13})/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
       view=auth_views.password_reset_confirm,
       name='base_password_reset_confirm',
       kwargs={'template_name': 'lib/password_reset_confirm.html'}),
    url(r'^password_reset_complete/$',
       view=auth_views.password_reset_complete,
       name='password_reset_complete',
       kwargs={'template_name': 'lib/password_reset_complete.html'}),


    # Поставщиики данных для виджетов
    url(r'^forms_widget_autocomplete/', view='forms_widget_autocomplete',
       name='forms_widget_autocomplete'),

    url(r'^tree_widget/(?P<application>\w+)/(?P<model_name>\w+)/$',
       view='tree_widget', name='tree_widget'),

    # url(r'^autocomplete_widget/(?P<application>\w+)/(?P<model_name>\w+)/$',
    #     view=views.autocomplete_widget, name='autocomplete_widget'),

    # Документция по БД
    url(r'^documentation/$', view='db_documentation', name='db_documentation'),

    url(r'^set_lang/(?P<code>\w{2})/$', view='set_lang', name='set_lang'),

    # Скрипт закрытия модального окна и обновления opener
    # Для переадресации сюда по success_url
    url(r'^close_modal_window/$', view='close_modal_window', name='close_modal_window'),
    url(r'^close_modal_window_no_reload/$', view='close_modal_window_no_reload', name='close_modal_window_no_reload'),



)

oys/urls.py
# coding=utf-8

from django.conf.urls import patterns, include, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
                       # Библиотеки
                       url(r'^grappelli/', include('grappelli.urls')),
                       url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^i18n/', include('django.conf.urls.i18n', namespace='i18n')),

                       # Проект
                       url(r'^', include('common.urls', namespace='common')),
                       url(r'^lib/', include('lib.urls', namespace='lib')),
                       url(r'^account/', include('account.urls', namespace='account')),
                       url(r'^calculator/', include('calculator.urls', namespace='calculator')),
                       url(r'^sale/', include('sale.urls', namespace='sale')),
)

calculator/models.py
# coding=utf-8
import uuid
from django.conf import settings
from django.db import models
from django.utils.translation import ugettext_lazy as _
from calculator.constants import DELIVERY_INTERVALS, DELIVERY_REGION
from calculator.operations import GetClassifier


PERSON_GENDER_CHOICES = (
    (1, _('Male')),
    (2, _('Female')),
)

VEHICLE_TRANSIT_CHOICES = (
    (0, _('No')),
    (1, _('Yes')),
)

PAYMENT_TYPES = (
    ('cash', _('Cash')),
    ('epay', _('Online payment'))
)


def get_choices(name):
    if name:
        return [(obj.id, _(obj.title)) for obj in GetClassifier(name).execute()]

    return [('', '-' * 9)]


class ContractCalculationAbstract(models.Model):
    u"""
    Абстрактный класс с типовыми данными по договору
    """

    # Системные
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    client = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True, editable=False,
                               verbose_name=_('client'))
    d_create = models.DateTimeField(_('creation date'), auto_now_add=True, editable=False, db_index=True)
    # Признак того, что договор оформлен в калькуляторе до конца (проставляется при окончании процесса оформления
    # в калькуляторе)
    is_completed = models.BooleanField(_('completed'), default=False, editable=False, db_index=True)
    # Признак того, что договор выпущен на стороне брокера (должен проставляться извне)
    is_issued = models.BooleanField(_('issued'), default=False, editable=False, db_index=True)

    # Состояние интерфейса процесса
    step = models.CharField(_('calculator step'), max_length=50)
    substep = models.CharField(_('calculator sub step'), max_length=50)
    layer = models.CharField(_('calculator layer'), max_length=50)

    # Общие данные о текущем расчете, условия договора
    main_product = models.CharField(_('main product ID'), max_length=10, null=True, blank=True)
    main_product_text = models.CharField(_('main product title'), max_length=100, null=True, blank=True)

    # Условия страхования
    d_start = models.DateField(_('contract start date'), null=True, blank=True)
    term_insurance = models.PositiveSmallIntegerField(_('term insurance'), null=True, blank=True)

    # Страхователь
    ins_person_pin = models.CharField(_('PIN'), max_length=9, null=True, blank=True)
    ins_person_lname = models.CharField(_('last name'), max_length=50, null=True, blank=True)
    ins_person_fname = models.CharField(_('first name'), max_length=50, null=True, blank=True)
    ins_person_mname = models.CharField(_('middle name'), max_length=50, null=True, blank=True)
    ins_person_gender = models.PositiveSmallIntegerField(_('gender'), choices=PERSON_GENDER_CHOICES, default=1)
    ins_person_birthday = models.DateField(_('birthday'), null=True, blank=True)
    ins_country = models.PositiveIntegerField(_('country'), null=True, blank=True)

    ins_index = models.CharField(_('postal index (ZIP)'), max_length=6, null=True, blank=True)
    ins_city = models.PositiveIntegerField(_('city'), null=True, blank=True)
    ins_city_custom = models.CharField(_('city (custom)'), max_length=50, null=True, blank=True)
    ins_address = models.CharField(_('address'), max_length=70, null=True, blank=True)
    ins_street = models.CharField(_('street'), max_length=50, null=True, blank=True)
    ins_house = models.CharField(_('house'), max_length=10, null=True, blank=True)
    ins_apartment = models.CharField(_('apartment'), max_length=10, null=True, blank=True)
    ins_phone = models.CharField(_('phone'), max_length=12, null=True, blank=True)
    ins_email = models.EmailField(_('email'), null=True, blank=True)

    # Доставка и оплата
    delivery_type = models.CharField(_('delivery type'), max_length=10, null=True, blank=True)
    delivery_date = models.DateField(_('delivery date'), null=True, blank=True)
    delivery_time = models.IntegerField(_('delivery time interval'), null=True, blank=True, choices=DELIVERY_INTERVALS)
    delivery_city = models.PositiveIntegerField(_('city'), null=True, blank=True)
    delivery_region = models.CharField(_('region'), max_length=50, blank=True, null=True, choices=DELIVERY_REGION)
    delivery_street = models.CharField(_('street'), max_length=50, null=True, blank=True)
    delivery_house = models.CharField(_('house'), max_length=10, null=True, blank=True)
    delivery_apartment = models.CharField(_('apartment'), max_length=10, null=True, blank=True)
    delivery_phone = models.CharField(_('phone'), max_length=12, null=True, blank=True)
    delivery_comment = models.TextField(_('comments'), null=True, blank=True)
    delivery_takeout = models.IntegerField(_('takeout point'), null=True, blank=True)
    delivery_email = models.EmailField(_('delivery email'), null=True, blank=True)

    # Платежи
    payment_type = models.CharField(_('payment type'), max_length=10, null=True, blank=True, choices=PAYMENT_TYPES)
    s_premium = models.FloatField(null=True)

    # Онлайн-оплата
    d_payment = models.DateTimeField(null=True)
    s_payment = models.FloatField(null=True)

    class Meta:
        app_label = 'calculator'
        abstract = True


class VehicleContract(ContractCalculationAbstract):
    u"""
    Комплексный договор по страхованию ТС (ОСАГО, Уверенный водитель, Простое КАСКО)
    """

    # Общие данные о текущем расчете, условия договора
    p2_selected = models.BooleanField(_('product 2 selected'), default=False)
    p11_selected = models.BooleanField(_('product 11 selected'), default=False)
    p12_selected = models.BooleanField(_('product 12 selected'), default=False)
    p2_id = models.PositiveIntegerField(_('p2 document id'), null=True, blank=True)
    p11_id = models.PositiveIntegerField(_('p11 document id'), null=True, blank=True)
    p12_id = models.PositiveIntegerField(_('p12 document id'), null=True, blank=True)

    # Страхователь наследуется

    # Автомобиль
    auto_type = models.PositiveIntegerField(_('vehicle type'))
    auto_mark = models.PositiveIntegerField(_('vehicle mark'))
    auto_model = models.PositiveIntegerField(_('vehicle model'))
    auto_engine_capacity = models.PositiveIntegerField(_('vehicle engine capacity'), null=True, blank=True)
    auto_payload = models.PositiveIntegerField(_('vehicle payload'), null=True, blank=True)
    cnt_seats = models.PositiveIntegerField(_('vehicle seats'), null=True, blank=True)
    auto_createyear = models.PositiveIntegerField(_('vehicle creation year'), null=True, blank=True)
    auto_vin = models.CharField('VIN', max_length=17, null=True, blank=True)
    auto_engine = models.CharField('EIN', max_length=17, null=True, blank=True)
    auto_chassis = models.CharField('CIN', max_length=17, null=True, blank=True)
    auto_number = models.CharField(_('vehicle registration number'), max_length=12)
    auto_region = models.PositiveIntegerField(_('vehicle registration region'))
    auto_cost = models.PositiveIntegerField(_('vehicle cost'))

    # Продукт ОСАГО
    p2_inscompany = models.PositiveSmallIntegerField(_('insurance company'), null=True, blank=True)
    ateshgah_beshlik = models.BooleanField(_('ateshgah beshlik'), default=False)
    ateshgah_icbariplus = models.BooleanField(_('ateshgah icbariplus'), default=False)
    ateshgah_superkasko = models.BooleanField(_('ateshgah superkasko'), default=False)

    # Продукт Уверенный водитель
    p11_inscompany = models.PositiveSmallIntegerField(_('insurance company'), null=True, blank=True)
    p11_product_option = models.CharField(_('station selection'), max_length=50, null=True, blank=True)
    p11_beneficiary = models.CharField(_('beneficiary'), max_length=10, null=True, blank=True)
    p11_bank_beneficiary = models.PositiveSmallIntegerField(_('bank'), null=True, blank=True)

    # Продукт Простое КАСКО
    p12_inscompany = models.PositiveIntegerField(_('insurance company'), null=True, blank=True)
    p12_beneficiary = models.CharField(_('beneficiary'), max_length=10, null=True, blank=True)
    p12_bank_beneficiary = models.PositiveIntegerField(_('bank'), null=True, blank=True)
    insurance_coverage = models.PositiveIntegerField(_('insurance sum'), null=True, blank=True)
    accidents_quantity = models.PositiveIntegerField(_('accidents quantity'), null=True, blank=True)
    evacuation = models.BooleanField(_('evacuation'), default=False)
    cvi_extension_sum = models.PositiveIntegerField(_('cvi extension sum'), null=True, blank=True)
    accident_ins_sum = models.PositiveIntegerField(_('accident insurance sum'), null=True, blank=True)
    accident_ins_drivers = models.PositiveSmallIntegerField(_('accident insurance drivers'), null=True, blank=True)
    additional_drivers = models.BooleanField(_('additional drivers'), default=False)
    additional_driver_2 = models.BooleanField(_('second additional driver'), default=False)

    # Владелец ТС
    ins_owner = models.BooleanField(_('insurant is vehicle owner'), default=True)
    owner_pin = models.CharField(_('PIN'), max_length=9, null=True, blank=True)
    owner_lname = models.CharField(_('last name'), max_length=50, null=True, blank=True)
    owner_fname = models.CharField(_('first name'), max_length=50, null=True, blank=True)
    owner_mname = models.CharField(_('middle name'), max_length=50, null=True, blank=True)
    owner_gender = models.PositiveSmallIntegerField(_('gender'), null=True, blank=True, choices=PERSON_GENDER_CHOICES)
    owner_birthday = models.DateField(_('birthday'), null=True, blank=True)
    owner_country = models.PositiveIntegerField(_('country'), null=True, blank=True)
    owner_index = models.CharField(_('postal index (ZIP)'), max_length=6, null=True, blank=True)
    owner_city = models.PositiveIntegerField(_('city'), null=True, blank=True)
    owner_city_custom = models.CharField(_('city (custom)'), max_length=50, null=True, blank=True)
    owner_address = models.CharField(_('address'), max_length=70, null=True, blank=True)

calculator/templates/calculator/steps/general/step_6.html
{% load i18n %}
<div class="b-form__block n-form__despolicy n-form__step clearfix" id="step-6">
    <div class="b-form__left clearfix">
        <div>
            <a href="#" class="pull-right b-item__edit j-calculator__reset">{% trans 'В начало' %}</a>
        </div>
        <div class="b-step__title n-title__ico {% block header_icon %}{% endblock %}">
            <h2>{% trans 'Оплата и доставка' %}</h2>
        </div>

        {# Доставка #}
        <div class="b-data__line clearfix">
            <div class="b-data__wr j-block__scr">
                <p class="b-title__sm">{% trans 'Доставка полиса' %}</p>

                <div class="b-data__wr col-sm-4">
                    <div class="row">
                        <input type="radio" data-window="1" name="delivery_type" id="id_delivery_type_courier"
                               value="courier" checked class="b-form__radio n-main__radio">
                        <label for="id_delivery_type_courier">{% trans 'Курьерская доставка' %}</label>
                    </div>
                </div>
{#                <div class="b-data__wr col-sm-4">#}
{#                    <div class="row">#}
{#                        <input type="radio" data-window="2" name="delivery_type" id="id_delivery_type_takeout"#}
{#                               value="takeout"#}
{#                               class="b-form__radio n-main__radio">#}
{#                        <label for="id_delivery_type_takeout">{% trans 'Забрать в точке продаж' %}</label>#}
{#                    </div>#}
{#                </div>#}
{#                <div class="b-data__wr col-sm-4">#}
{#                    <div class="row">#}
{#                        <input type="radio" data-window="3" name="delivery_type" id="id_delivery_type_email"#}
{#                               value="email"#}
{#                               class="b-form__radio n-main__radio">#}
{#                        <label for="id_delivery_type_email">{% trans 'Отправить по email' %}</label>#}
{#                    </div>#}
{#                </div>#}

                <div class="clearfix"></div>

                {# Адрес для доставки курьером #}
                <div class="b-block__scr n-src__window_1" data-window="1" style="display: block">
                    <div class="b-data__line n-line__delivery">
                        <div class="b-label__wr col-md-4 col-xs-5">
                            <div class="row"><label for="id_delivery_date">{% trans 'Дата доставки' %}</label></div>
                        </div>
                        <div class="b-input__wr col-md-2 col-xs-5">
                            <div class="row clearfix">
                                <input type="text" name="delivery_date" id="id_delivery_date"
                                       class="b-input j-delivery__date n-calendar">
                            </div>
                        </div>
                        <div class="col-lg-1 pull-right"></div>
                        <div class="col-lg-4 col-xs-12 flat-wr b-input__wr clearfix">
                            <div class="row">
                                <div class="b-label__wr col-md-4  col-xs-5">
                                    <div class="row">
                                        <label for="id_delivery_time">{% trans 'Время' %}</label>
                                    </div>
                                </div>
                                <div class="b-input__wr col-md-7 col-xs-5">
                                    <div class="row">
                                        <select id="id_delivery_time" name="delivery_time" class="b-select">
                                            <option value="1">09:00 - 10:00</option>
                                            <option value="2">10:00 - 11:00</option>
                                            <option value="3">11:00 - 12:00</option>
                                            <option value="4">12:00 - 13:00</option>
                                            <option value="5">13:00 - 14:00</option>
                                            <option value="6">14:00 - 15:00</option>
                                            <option value="7">15:00 - 16:00</option>
                                            <option value="8">16:00 - 17:00</option>
                                            <option value="9">17:00 - 18:00</option>
                                            <option value="10">18:00 - 19:00</option>
                                            <option value="11">19:00 - 20:00</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="field-error"><span></span></div>
                    </div>

                    {# Город #}
                    {% trans 'Город' as city_tr %}
                    {% include 'calculator/steps/g_selection_field.html' with field_name='delivery_city' field_label=city_tr objects=delivery_cities %}

                    {# Район #}
                    {% trans 'Район' as region_tr %}
                    {% include 'calculator/steps/g_selection_field.html' with field_name='delivery_region' field_label=region_tr objects=delivery_regions %}

                    <div class="b-data__line">
                        <div class="b-label__wr col-md-4 col-xs-5">
                            <div class="row"><label for="id_delivery_street">{% trans 'Улица' %}</label></div>
                        </div>
                        <div class="b-input__wr col-md-7 col-xs-6">
                            <div class="row">
                                <input type="text" name="delivery_street" id="id_delivery_street" class="b-input">
                            </div>
                        </div>
                        <div class="field-error"><span></span></div>
                    </div>

                    <div class="b-data__line">
                        <div class="b-label__wr col-md-4 col-xs-5">
                            <div class="row"><label for="id_delivery_house">{% trans 'Дом' %}</label></div>
                        </div>
                        <div class="b-input__wr col-md-2 col-xs-5">
                            <div class="row">
                                <input type="text" name="delivery_house" id="id_delivery_house" class="b-input w-100">
                            </div>
                        </div>
                        <div class="col-lg-1 pull-right"></div>
                        <div class="col-lg-4 col-xs-12 flat-wr b-input__wr clearfix">
                            <div class="row">
                                <div class="b-label__wr col-md-4 col-xs-5">
                                    <div class="row">
                                        <label for="id_delivery_apartment">{% trans 'Квартира' %}</label>
                                    </div>
                                </div>
                                <div class="b-input__wr col-md-7 col-xs-5">
                                    <div class="row">
                                        <input type="text" name="delivery_apartment" id="id_delivery_apartment" class="b-input w-100">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="field-error"><span></span></div>
                    </div>

                    <div class="b-data__line">
                        <div class="b-label__wr col-md-4 col-xs-5">
                            <div class="row"><label for="id_delivery_phone">{% trans 'Телефон' %}</label></div>
                        </div>
                        <div class="b-input__wr col-md-7 col-xs-6">
                            <div class="row">
                                <input type="text" name="delivery_phone" id="id_delivery_phone" class="b-input">
                            </div>
                        </div>
                        <div class="field-error"><span></span></div>
                    </div>

                    <div class="b-data__line">
                        <div class="b-label__wr col-md-4 col-xs-5">
                            <div class="row">
                                <label for="id_delivery_comment">{% trans 'Комментарий' %}</label>
                            </div>
                        </div>
                        <div class="b-input__wr col-md-7 col-xs-6">
                            <div class="row">
                                <textarea name="delivery_comment" id="id_delivery_comment" class="b-textarea"></textarea>
                            </div>
                        </div>
                        <div class="field-error"><span></span></div>
                    </div>
                </div>

                {# Выбор точки самовывоза #}
{#                <div class="b-block__scr n-src__window_2" data-window="2">#}
{#                    <div class="b-data__line n-adress__map">#}
{##}
{#                        <div class="b-data__wr">#}
{#                            <input type="radio" name="delivery_takeout" id="id_delivery_takeout_1" class="b-form__radio" value="1" data-latitude="40.398417" data-longitude="49.832223" data-zoom="17" checked>#}
{#                            <label for="id_delivery_takeout_1">#}
{#                                A-Group Insurance Company г. Баку, Нобелевский пр-т. 15, 22-ый этаж#}
{#                            </label>#}
{#                        </div>#}
{##}
{#                        <div class="b-data__wr">#}
{#                            <input type="radio" name="delivery_takeout" id="id_delivery_takeout_2" class="b-form__radio" value="2" data-latitude="40.379821" data-longitude="49.8788296" data-zoom="17">#}
{#                            <label for="id_delivery_takeout_2">#}
{#                                Amrah Sigorta г. Баку, Нобелевский пр-т. 15, 22-ый этаж#}
{#                            </label>#}
{#                        </div>#}
{##}
{#                        <div class="b-data__wr">#}
{#                            <input type="radio" name="delivery_takeout" id="id_delivery_takeout_3" class="b-form__radio" value="3" data-latitude="40.379821" data-longitude="49.8788296" data-zoom="17">#}
{#                            <label for="id_delivery_takeout_3">#}
{#                                Ateshgah Sigorta (Азадлыг) г. Баку, Нобелевский пр-т. 15, 22-ый этаж#}
{#                            </label>#}
{#                        </div>#}
{##}
{#                        <div class="field-error"><span></span></div>#}
{##}
{#                    </div>#}
{#                    <div id="map_list" class="b-points__map"></div>#}
{#                </div>#}

                {# Адрес электорнной почты для отправки #}
{#                <div class="b-block__scr n-src__window_3" data-window="3">#}
{#                    <div class="b-data__line n-delivery__email">#}
{#                        <div class="b-label__wr col-md-4 col-xs-5">#}
{#                            <div class="row">#}
{#                                <label for="id_delivery_email">E-mail</label>#}
{#                            </div>#}
{#                        </div>#}
{#                        <div class="b-input__wr col-md-7 col-xs-6">#}
{#                            <div class="row">#}
{#                                <input type="text" name="delivery_email" id="id_delivery_email" class="b-input">#}
{#                            </div>#}
{#                        </div>#}
{##}
{#                        <div class="field-error"><span></span></div>#}
{#                    </div>#}
{#                </div>#}

            </div>

        </div>

        {# Оплата #}
        <div class="b-data__line clearfix">
            <div class="b-data__wr">
                <p class="b-title__sm">{% trans 'Оплата' %}</p>

                <div class="row">
                    <div class="b-data__wr col-xs-6">
                        <input type="radio" name="payment_type" id="id_payment_type_cash" class="b-form__radio" value="cash" checked>
                        <label for="id_payment_type_cash">{% trans 'Наличным курьеру' %}</label>
                    </div>
                    <div class="b-data__wr col-xs-6">
                        <input type="radio" data-window="1" name="payment_type" id="id_payment_type_epay" class="b-form__radio" value="epay">
                        <label for="id_payment_type_epay">{% trans 'Онлайн оплата' %}</label>
                    </div>
                </div>
            </div>

            <div class="field-error"><span></span></div>
        </div>

        <div class="b-data__line clearfix"></div>

    </div>

    <div class="b-form__right clearfix">
        <div class="b-right__info j-right__info-fixed">
            {% block right_sideboard %}{% endblock %}
            <button type="button" class="order button j-last__show j-next__click e-show">{% trans 'Завершить оформление' %}</button>
        </div>
    </div>

</div>

calculator/templates/calculator/steps/general/step_7.html
{% load i18n %}
<div class="b-form__block n-last__step n-form__step clearfix" id="step-7">
    <div class="b-last__step col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1">
        <h2>{% trans 'Поздравляем вас! Вы&nbsp;застрахованы!' %}</h2>
        <p>{% trans 'В ближайшее время с Вами свяжется оператор для подтверждения адреса доставки' %}</p>
    </div>
</div>