lib/urls.py
# coding=utf-8

from django.conf.urls import patterns, url
from django.contrib.auth import views as auth_views
from .forms import CustomPasswordResetForm

urlpatterns = patterns(
    'lib.views',

    # Управление учетными записями
    url(r'^login/$',
       view=auth_views.login,
       name='login',
       kwargs={'template_name': 'lib/login.html'}),
    url(r'^logout/$',
       view=auth_views.logout,
       name='logout',
       kwargs={'template_name': 'lib/logout.html'}),

    # Смена пароля
    url(r'^password_change/$', view=auth_views.password_change,
       name='password_change',
       kwargs={'template_name': 'lib/password_change.html',
               'post_change_redirect': '/password_change_done/'}),
    url(r'^password_change_done/$',
       view=auth_views.password_change_done,
       name='password_change_done',
       kwargs={'template_name': 'lib/password_change_done.html'}),

    # Сброс и восстановление пароля
    url(r'^password_reset/$',
        view=auth_views.password_reset,
        name='password_reset',
        kwargs={
            'template_name': 'lib/password_reset.html',
            'email_template_name': 'lib/password_reset_email.html',
            'post_reset_redirect': '/password_reset_done/',
            'password_reset_form': CustomPasswordResetForm,
        }),
    url(r'^password_reset_done/$',
       view=auth_views.password_reset_done,
       name='password_reset_done',
       kwargs={'template_name': 'lib/password_reset_done.html'}),
    url(r'^password_reset_confirm/(?P<uidb64>[0-9A-Za-z]{1,13})/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
       view=auth_views.password_reset_confirm,
       name='base_password_reset_confirm',
       kwargs={'template_name': 'lib/password_reset_confirm.html'}),
    url(r'^password_reset_complete/$',
       view=auth_views.password_reset_complete,
       name='password_reset_complete',
       kwargs={'template_name': 'lib/password_reset_complete.html'}),


    # Поставщиики данных для виджетов
    url(r'^forms_widget_autocomplete/', view='forms_widget_autocomplete',
       name='forms_widget_autocomplete'),

    url(r'^tree_widget/(?P<application>\w+)/(?P<model_name>\w+)/$',
       view='tree_widget', name='tree_widget'),

    # url(r'^autocomplete_widget/(?P<application>\w+)/(?P<model_name>\w+)/$',
    #     view=views.autocomplete_widget, name='autocomplete_widget'),

    # Документция по БД
    url(r'^documentation/$', view='db_documentation', name='db_documentation'),

    url(r'^set_lang/(?P<code>\w{2})/$', view='set_lang', name='set_lang'),

    # Скрипт закрытия модального окна и обновления opener
    # Для переадресации сюда по success_url
    url(r'^close_modal_window/$', view='close_modal_window', name='close_modal_window'),
    url(r'^close_modal_window_no_reload/$', view='close_modal_window_no_reload', name='close_modal_window_no_reload'),



)

oys/urls.py
# coding=utf-8

from django.conf.urls import patterns, include, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
                       # Библиотеки
                       url(r'^grappelli/', include('grappelli.urls')),
                       url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^i18n/', include('django.conf.urls.i18n', namespace='i18n')),

                       # Проект
                       url(r'^', include('common.urls', namespace='common')),
                       url(r'^lib/', include('lib.urls', namespace='lib')),
                       url(r'^account/', include('account.urls', namespace='account')),
                       url(r'^calculator/', include('calculator.urls', namespace='calculator')),
                       url(r'^sale/', include('sale.urls', namespace='sale')),
)

lib/models.py
# coding=utf-8

from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.conf import settings


class LogAccess(models.Model):
    u""" Тут лежат записи логгирования обращений к серверу """

    user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True,
                             related_name='log_access')
    d_create = models.DateTimeField(null=False, auto_now_add=True)
    remote_addr = models.GenericIPAddressField(null=False)
    remote_host = models.CharField(max_length=100, null=True, blank=True)
    http_referer = models.CharField(max_length=1000, null=True, blank=True)
    path = models.CharField(max_length=1000, null=True, blank=True)
    post = models.TextField(null=True)

    class Meta:
        app_label = 'lib'


# Статусы доставки сообщений (возвращаются процедурой получения детального отчета)
SMS_STATUS = (
    (1, _('Message is queued')),
    (2, _('Message was successfully delivered')),
    (3, _('Message delivery failed')),
    (4, _('Message was removed from list')),
    (5, _('System error'))
)


class SmsTask(models.Model):
    u"""
    Задачи на отправку СМС
    """
    internal_id = models.CharField(max_length=36, db_index=True, null=True, blank=True,
                                   verbose_name=_('internal id'))
    external_id = models.CharField(max_length=50, db_index=True, null=True, blank=True,
                                   verbose_name=_('external task id'))
    sender_title = models.CharField(max_length=100, verbose_name=_('sender title'))
    task_type = models.CharField(max_length=50)

    class Meta:
        app_label = 'lib'


class SmsTaskMessage(models.Model):
    u"""
    Сообщения, отправляемые в рамках задачи на отправку
    """
    task = models.ForeignKey(SmsTask, related_name='messages')
    msisdn = models.CharField(max_length=12, verbose_name='ISDN', db_index=True)
    message = models.TextField(blank=True, null=True, verbose_name=_('message'))
    # Статус сообщений, собирается командами статуса
    status = models.PositiveIntegerField(default=1, verbose_name=_('status'), choices=SMS_STATUS)
    status_change = models.DateTimeField(auto_now_add=True, verbose_name=_('last status change'))
    # Системные поля
    created = models.DateTimeField(auto_now_add=True, blank=True, null=True, db_index=True, editable=False, verbose_name=_('created'))

    class Meta:
        app_label = 'lib'

lib/forms.py
# coding=utf-8

from django.forms import Form, CharField, PasswordInput, ValidationError
from django.contrib import auth
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.forms import PasswordResetForm, get_user_model

User = get_user_model()

class LoginForm(Form):
    u""" Форма входа """

    username = CharField(max_length=50, label=_('Username'))
    password = CharField(max_length=50, label=_('Password'),
                         widget=PasswordInput())

    def clean(self):
        cleaned_data = super(LoginForm, self).clean()

        if 'username' in cleaned_data and 'password' in cleaned_data:
            user = auth.authenticate(username=cleaned_data['username'],
                                     password=cleaned_data['password'])
            if user is None or not user.is_active:
                raise ValidationError(_(u'No active user'))

        return cleaned_data


class CustomPasswordResetForm(PasswordResetForm):

    def clean_email(self):
        email = self.cleaned_data.get("email")
        if not User.objects.filter(email__iexact=email, is_active=True).exists():
            raise ValidationError(u'Пользователь не найден')
        return email

lib/views.py
# coding=utf-8

import json
import re
from collections import OrderedDict


from django.shortcuts import render
from django.http import HttpResponse, HttpResponseForbidden, HttpResponseRedirect
from lib.utils import get_model
from django.db.models import get_app, get_models
from django.db import connection
from .decorators import ajax_response
from django.utils.module_loading import import_by_path
from django.conf import settings
from django.utils import translation


def tree_widget(request, application, model_name):
    u""" Поставляет данные для иерархического поля """
    data = []

    if not request.is_ajax():
        return HttpResponseForbidden(u'Возможно обращение только по ajax')

    objects = get_model(application, model_name).objects

    node_id = request.GET['node_id']
    if node_id:
        objects = objects.filter(parent_id=node_id)
    else:
        objects = objects.filter(parent_id__isnull=True)

    for node in objects.iterator():
        title = unicode(node)
        has_children = node.children.exists()

        data.append({"id": node.id, "text": title, 'children': has_children, 'icon': False})

    return HttpResponse(json.dumps(data), content_type="application/json")


@ajax_response
def forms_widget_autocomplete(request):
    u'''
    Поставляет данные для поля - автоподстановка
    Забирает данные у функции-обработчика
    и отдает их для списка автодополнения
    '''

    if not request.is_ajax():
        return HttpResponseForbidden(u'Возможно обращение только по ajax')

    params = request.GET

    term = params.get('q')
    handler_path = params.get('handler_path')

    # Чистим лишние параметры для передачи в обработчик
    _params = {}
    for k in params.keys():
        if k in ('q', 'handler_path', '_'):
            continue
        _params[k] = params.get(k)

    handle_function = import_by_path(handler_path)
    res = handle_function(request=request, term=term, params=_params)

    return res


def db_documentation(request):
    u'''
    Собирает данные о представлении моделей
    в базе данных
    '''

    def _get_model_info(model):

        fields_meta = {}
        fields = model._meta.fields
        for field in fields:
            field_type = field.get_internal_type()

            ctx = {}

            if hasattr(field, 'max_length'):
                ctx.update({'max_length': field.max_length})

            if hasattr(field, 'max_digits') and hasattr(field, 'decimal_places'):
                ctx.update({'max_digits': field.max_digits, 'decimal_places': field.decimal_places})

            if hasattr(field, 'column'):
                ctx.update({'column': field.name})
            key = field.name + '_id' if field_type == 'ForeignKey' else field.name
            if field_type == 'ForeignKey':
                fields_meta[key] = {
                    'name': field.verbose_name,
                    'type': 'integer',
                    'is_null': field.null,
                    'db_table': field.rel.to._meta.db_table
                }
            else:
                type = connection.creation.data_types.get(field.__class__.__name__)
                type = str(type % ctx) if type else 'varchar(250)'
                try:
                    check = re.search(' CHECK(.+)', type)
                    if check.group(0):
                        check = check.group(0)
                        type = type.replace(check, '')
                except AttributeError:
                    check = ''
                fields_meta[key] = {
                    'name': field.verbose_name,
                    'type': type % ctx if type else 'FILE',
                    'is_null': field.null,
                    'check': check,
                }

        return {'db_table': model._meta.db_table,
                'verbose_name': model._meta.verbose_name,
                'docstring': model.__doc__,
                'fields': fields_meta}

    # Перебираем приложения
    applications = OrderedDict()
    for app_name in sorted(settings.INSTALLED_APPS):
        try:
            app = get_app(app_name)
        except:
            continue

        app_models_name = []
        app_models_data = {}

        for model in get_models(app):
            model_info = _get_model_info(model)
            db_table = model_info['db_table']

            app_models_name.append(db_table)

            app_models_data[db_table] = {
                'db_table': model_info['db_table'],
                'verbose_name': model_info['verbose_name'],
                'docstring': model_info['docstring'],
                'fields': model_info['fields']
            }

        if not app_models_name:
            continue

        sorted_models = [app_models_data[db_table_] for db_table_ in sorted(app_models_name)]

        applications[app_name] = sorted_models

    doc = render(request, 'lib/documentation.html', {'applications': applications})
    return doc


def set_lang(request, code):
    u""" Переключить язык и вернуться на предыдущий раздел """

    request.session[translation.LANGUAGE_SESSION_KEY] = code
    return HttpResponseRedirect(request.GET['back_url'])


def close_modal_window(request):
    return render(request, 'lib/close_modal_window.html')


def close_modal_window_no_reload(request):
    return HttpResponse('''
        <script>
            window.close()
        </script>
    ''')

lib/templates/lib/base.html
{% load i18n %}
{% load lib_filters %}
{% load lib_tags %}


<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block page_title %}SmartBPS{% endblock %}</title>
    <link type="image/x-icon" rel="shortcut icon" href="{{ STATIC_URL }}lib/favicon.ico" />

    {% block css %}
        <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}lib/bootstrap/css/bootstrap.min.css"/>
        <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}lib/bootstrap/css/bootstrap-theme.min.css"/>

        <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}lib/bootstrap_datepicker/css/datepicker3.css"/>
        <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}lib/select2/css/select2.min.css"/>
        <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}lib/style.css"/>
        <link rel="stylesheet" href="{{ STATIC_URL }}lib/spinners16/css/spinners-16.css">
        <link rel="stylesheet" href="{{ STATIC_URL }}lib/spinners16/css/animation.css">
        <!--[if IE 7]><link rel="stylesheet" href="{{ STATIC_URL }}lib/spinners16/css/spinners-16-ie7.css"><![endif]-->

        <link rel="stylesheet" href="{{ STATIC_URL }}lib/intro_js/css/introjs.min.css">
        <link rel="stylesheet" href="{{ STATIC_URL }}lib/intro_js/css/introjs-nassim.css">

    {% endblock css %}

    {% block javascript_header %}
        <script type="text/javascript" src="{{ STATIC_URL }}lib/jquery/jquery-1.11.0.min.js"></script>
        <script type="text/javascript" src="{{ STATIC_URL}}lib/i18next/i18next-1.7.7.min.js"></script>
        <script type="text/javascript">
            var language_code = '{{ LANGUAGE_CODE }}'
            var static_url = '{{STATIC_URL}}'
        </script>
    {% endblock javascript_header %}
</head>
<body>

{% block body %}

{% block navigation %}

    <nav class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'home' %}">{% block navbar_brand %}SmartBPS{% endblock %}</a>
        </div>
        <div class="navbar-collapse collapse">



            <ul class="nav navbar-nav">
                {% block navigation_items %}
                {% endblock %}
            </ul>

            <ul class="nav navbar-nav navbar-right">
                {% block navigation_right %}
                    <li><a class='btn btn-link' onClick="introJs().start();">
                        <span class="glyphicon glyphicon-question-sign"></span>
                    </a></li>

                    {% if user.is_authenticated %}
                        <li class="dropdown" data-intro="Вход, выход и изменение языка">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                {{ user.get_short_name }} <b class="caret"></b>
                            </a>
                            {% block dropdown %}
                                <ul class="dropdown-menu">
                                    {% block navbar_user_dropdown %}
                                    <li><a href="#" onClick="$('#modal_setlang').modal('show');">
                                        {% trans 'Change language' %}
                                    </a></li>
                                    <li><a href="{% url 'lib:password_change' %}">
                                        {% trans 'Change password' %}</a></li>
                                    <li><a href="{% url 'lib:logout' %}">{% trans 'Logoff' %}</a></li>
                                    {% endblock navbar_user_dropdown %}
                                </ul>
                            {% endblock %}
                        </li>
                    {% else %}
                        <li><a class='btn btn-link' href="{% url 'lib:login' %}">{% trans 'Login' %}</a></li>
                    {% endif %}
                {% endblock navigation_right %}
            </ul>
        </div>
    </nav>

{% endblock navigation %}


<div class="container container-full">

    {% block breadcrumb %}{% endblock %}


    {% block body_messages %}
        {% if messages %}
            <div id="site_messages">
            {% for message in messages %}
                <div class="alert alert-sm {{message.tags}}">{{message|safe}}</div>
            {% endfor %}
            </div>
        {% endif %}
    {% endblock %}


    {% block body_content %}

    {% endblock %}

</div>

{% endblock body %}

{% block javascript %}

    <script type="text/javascript" src="{{ STATIC_URL }}lib/jquery/jquery-migrate-1.2.1.min.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}lib/date.format.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}lib/jquery/jquery.maskedinput.min.js"></script>

    <script type="text/javascript" src="{{ STATIC_URL }}lib/bootstrap/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}lib/bootstrap_datepicker/js/bootstrap-datepicker.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}lib/bootstrap_datepicker/js/locales/bootstrap-datepicker.ru.js"></script>

    <script type="text/javascript" src="{{ STATIC_URL }}lib/select2/js/select2.min.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}lib/select2/js/i18n/ru.js"></script>

    <script type="text/javascript" src="{{ STATIC_URL }}lib/intro_js/js/intro.min.js"></script>

    <script type="text/javascript" src="{{ STATIC_URL }}lib/script.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}lib/utils.js"></script>
{% endblock javascript %}

{% block modals %}


    <div id="modal_setlang" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">

                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">{% trans 'Change language' %}</h4>
                </div>

                <form action="{% url 'i18n:set_language' %}" method="post">


                <div class="modal-body">
                    {% csrf_token %}
                    <input name="next" type="hidden" value="{{ redirect_to }}" />

                    <select name="language" class="form-control">
                        {% get_language_info_list for LANGUAGES as languages %}
                        {% for language in languages %}
                        <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected="selected"{% endif %}>
                            {{ language.name_local }} ({{ language.code }})
                        </option>
                        {% endfor %}
                    </select>

                </div>

                <div class="modal-footer">
                    <input type="submit" class="btn btn-primary" value="{% trans 'Change' %}" />
                </div>

                </form>

            </div>
        </div>
    </div>
{% endblock modals %}

</body>
</html>

lib/templates/lib/base_email.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
</head>
<body>
    <div class="container-fluid">
    {% block body %}
    {% endblock %}
    </div>
</body>
</html>

lib/templates/lib/close_modal_window.html
<script>
    window.opener.location.reload()
    window.close()
</script>

lib/templates/lib/documentation.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="/static/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen">
    <script type="text/javascript" src="{{ STATIC_URL }}lib/jquery/jquery-1.11.0.min.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}lib/bootstrap/js/bootstrap.min.js"></script>
    <script type="text/javascript">

        function select_app(app_name) {
            scroll_to('application_'+app_name)
        }

        function scroll_to(hash) {
            var position = $('a[name="' + hash + '"]').offset().top
            $('html, body').animate({
                scrollTop: position - 70
            }, 300);
        }
    </script>

</head>
<style>

    body {
        padding-top: 70px;
    }

    th {
        text-align: center;
    }

    a:hover {
        text-decoration: none;
    }
    a {
        cursor: pointer
    }

    .ancor {
        position: relative;
        padding-top: 70px;
    }

    #navbar_scrollable > ul.nav > li > a {
        padding: 5px;
    }

    
    @media (min-width: 768px) {
        #navbar_scrollable {
            position: fixed;
            top: 70px;
            bottom: 10px;
            overflow-y: auto;
        }
    }

</style>

<body>

    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">SmartBPS</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Приложения <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                {% for app_name, models in applications.items %}
                    <li><a onClick="select_app('{{app_name}}')">{{app_name}}</a></li>
                {% endfor %}
              </ul>
            </li>

          </ul>
        </div>
      </div>
      </div>
    </nav>


    <div class="container">
        <div class="row">
            {# Таблицы #}
            <div class="col-sm-8">
                <div id="tables_scrollable">
                    {% for app_name, models in applications.items %}
                        

                        <h1 id='application_{{ app_name }}'>
                            <A NAME="application_{{ app_name }}" href="#application_{{ app_name }}" class='ancor'></A>
                            Приложение {{app_name}}
                        </h1>
                        
                        {% for model in models %}
                            
                            <a onClick="scroll_to('{{ model.db_table }}')">
                                <span class="label label-default">
                                {{ model.db_table }}</span>
                            </a>
                            
                        {% endfor %}

                        {% for model in models %}

                            <h3>
                                <A NAME="{{ model.db_table }}" href="#{{ model.db_table }}"></A>
                                {{ model.verbose_name }}
                                <small>
                                    {{ model.db_table }} 
                                </small>
                                
                            </h3>

                            {{model.docstring}}
                            <table class="table table-striped table-bordered table-hovered table-condensed">
                                <tr>
                                    <th>Название</th>
                                    <th>Тип данных</th>
                                    <th>Ограничение</th>
                                    <th>Комментарий</th>
                                </tr>
                                {% for field_key, field in model.fields.items %}
                                <tr>
                                    <td>{{ field_key }}</td>
                                    <td>{{ field.type }}</td>
                                    <td>
                                        {% if not field.is_null %}not null{% endif %}
                                        {% if field.check %}<br>{{ field.check }}{% endif %}
                                    </td>
                                    <td>
                                        {% if field.name %}
                                            {{ field.name }}
                                        {% endif %}

                                        {% if field.db_table %} 
                                            <br>ссылается на <a onClick="scroll_to('{{ field.db_table }}')">{{ field.db_table }}</A>
                                        {% endif %}
                                    </td>
                                </tr>
                                {% endfor %}
                            </table>
                        {% endfor %} 
                        
                    {% endfor %} 
                </div>
            </div>

            <div class="col-sm-4">
                <div id='navbar_scrollable' class='well'>
                    <ul class="nav">
                        {% for app_name, models in applications.items %}
                            <li role="presentation" class="disabled">
                                <a href="#">{{app_name}}</a>
                            </li>
                            {% for model in models %}
                                <li>
                                    <a onClick="scroll_to('{{ model.db_table }}')">{{ model.db_table }}</a>
                                </li>
                            {% endfor %}
                        {% endfor %}
                    </ul>
                </div>
            </div>

        </div>
    </div>

</body>

lib/templates/lib/login.html
{% extends 'lib/modal.html' %}
{% load lib_tags %}
{% load i18n %}

{% block body_modal_header %}{% trans 'Login' %}{% endblock %}

{% block body_modal_body %}
    {% csrf_token %}
    {% form_bootstrap form layout="horizontal" %}
{% endblock %}

{% block body_modal_footer %}
    <input type='submit' class="btn btn-primary" value='{% trans 'Login' %}'>
    <a href="{% url 'home' %}" class="btn">{% trans 'Cancel' %}</a>
    <a href="{% url 'lib:password_reset' %}" class="btn btn-link">{% trans 'Forgot your password' %}?</a>
{% endblock %}	

lib/templates/lib/logout.html
{% extends 'lib/modal.html' %}
{% load i18n %}


{% block body_modal_header %}{% trans 'Logoff' %}{% endblock %}

{% block body_modal_body %}
	{% trans 'All the best.<br>Thank you for the time spent' %}
{% endblock %}

{% block body_modal_footer %}
	<a href="{% url 'lib:login' %}" class="btn btn-primary">{% trans 'Login' %}</a>
	<a href="{% url 'home' %}" class="btn">{% trans 'Home' %}</a>	 
{% endblock %}

lib/templates/lib/modal.html
{% extends 'lib/base.html' %}

{% block navigation %}{% endblock %}
{% block body_messages %}{% endblock %}
{% block javascript %}{% endblock %}

{% block css %}
    {{block.super}}
    <style type="text/css">
        body { background-color: #eee; }
    </style>
{% endblock css %}

{% block body %}

    <div class="modal-dialog">
        <div class="modal-content">

            <div class="modal-header">
                <h3>{% block body_modal_header %}{% endblock %}</h3>
            </div>

            <form method='post' class="form-horizontal" role="form">
                <div class="modal-body">
                    {% block body_modal_body %}

                    {% endblock %}
                </div>
                <div class="modal-footer">
                    {% block body_modal_footer %}

                    {% endblock %}
                </div>
            </form>

        </div>
    </div>

{% endblock body %}

lib/templates/lib/password_change.html
{% extends 'lib/modal.html' %}
{% load lib_tags %}
{% load i18n %}


{% block body_modal_header %}{% trans 'Change password' %}{% endblock %}

{% block body_modal_body %}
	{% csrf_token %}
	{% form_bootstrap form layout="horizontal" label_weight=6 %}
{% endblock %}

{% block body_modal_footer %}
	<input type='submit' class="btn btn-primary" value='{% trans "Change" %}'>
	<a href="{% url 'home' %}" class="btn">{% trans "Cancel" %}</a>	 
{% endblock %}	

lib/templates/lib/password_change_done.html
{% extends 'lib/modal.html' %}
{% load i18n %}

{% block body_modal_header %}{% trans 'Change Password' %}{% endblock %}

{% block body_modal_body %}
    {% trans 'The password has been successfully changed' %}
{% endblock %}

{% block body_modal_footer %}
    <a href="{% url 'home' %}" class="btn btn-primary">{% trans 'Home' %}</a>   
{% endblock %}  

lib/templates/lib/password_reset.html
{% extends 'lib/modal.html' %}
{% load i18n %}
{% load lib_tags %}

{% block body_modal_header %}{% trans 'Recover password' %}{% endblock %}

{% block body_modal_body %}
	<div class='alert alert-info'>
		Введите ваш адрес электронной почты.
		На него будет отправлена ссылка для восстановления пароля
		с дальнейшими инструкциями.
	</div>

	{% csrf_token %}
	{% form_bootstrap form layout="horizontal" label_weight=5 %}  
{% endblock %}

{% block body_modal_footer %}
    <input type='submit' class="btn btn-primary" value='{% trans 'Restore' %}'>
	<a href="{% url 'home' %}" class="btn">{% trans 'Cancel' %}</a>	
{% endblock %} 

lib/templates/lib/password_reset_email.html
Добрый день, {{user.get_full_name}}.

Кто-то от вашего имени запросил изменение восстановление пароля в {{site_name}}.
Если это были вы, то для восстановления пароля, перейдите по адресу:

{{ protocol}}://{{ domain }}{% url 'lib:base_password_reset_confirm' uidb64=uid token=token %}

Если это делали не вы, то можете ничего не делать.